import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  scrollContent: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    marginRight: 12,
    padding: 10,
  },
  headerTitle: {
    fontSize: 22,
    color: '#ffffff',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#1A1A1A',
    color: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 12,
  },
  inputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfInput: {
    flex: 1,
    backgroundColor: '#1A1A1A',
    color: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 12,
    marginHorizontal: 4,
  },
  orderSummary: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 15,
    color: '#888888',
    fontWeight: '400',
  },
  summaryValue: {
    fontSize: 15,
    color: '#ffffff',
    fontWeight: '500',
  },
  freeShippingBadge: {
    backgroundColor: '#2ecc71',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  freeShippingText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
  },
  totalLabel: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: '700',
  },
  totalValue: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: '700',
  },
  placeOrderButton: {
    backgroundColor: '#FF0080',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    width: '100%',
  },
  placeOrderButtonDisabled: {
    opacity: 0.5,
  },
  placeOrderText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#2ecc71',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  successText: {
    fontSize: 24,
    color: '#ffffff',
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  orderNumberText: {
    fontSize: 16,
    color: '#888888',
    fontWeight: '400',
    marginBottom: 32,
    textAlign: 'center',
  },
  viewOrdersButton: {
    backgroundColor: '#FF0080',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 40,
    alignItems: 'center',
  },
  viewOrdersText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  errorText: {
    color: '#e74c3c',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 12,
  },
  orderTotalText: {
    color: '#999',
    fontSize: 16,
    marginTop: 8,
  },
  shippingAddressPreview: {
    marginTop: 20,
    marginBottom: 8,
  },
  addressPreviewText: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 22,
  },
  addressChangeNote: {
    color: '#888',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 8,
  },
});

export default styles;
