import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollViewContent: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 20,
    },
    backgroundImage: {
        flex: 1,
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    contentContainer: {
        flex: 1,
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    topSection: {
        alignItems: 'center',
        marginBottom: 20,
        position: 'relative',
    },
    backButton: {
        position: 'absolute',
        left: 0,
        top: 10,
        padding: 10,
        borderRadius: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    roleIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginTop: 10,
    },
    roleIndicatorText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 6,
    },
    avatar: {
        width: 200,
        height: 140,
        marginTop: 10,
    },
    inputContainer: {
        width: '100%',
        marginBottom: 10,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#333',
        borderRadius: 8,
        paddingHorizontal: 15,
        marginBottom: 15,
        borderColor: '#4B0981',
        borderWidth: 1,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        height: 50,
    },
    phoneInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#333',
        borderRadius: 8,
        marginBottom: 15,
        borderColor: '#4B0981',
        borderWidth: 1,
    },
    flagContainer: {
        width: 60,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#333',
        borderTopLeftRadius: 8,
        borderBottomLeftRadius: 8,
        borderRightColor: '#4B0981',
        borderRightWidth: 1,
    },
    flagButton: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    phoneNumberContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: 10,
    },
    callingCodeText: {
        color: '#fff',
        fontSize: 16,
        marginRight: 5,
    },
    phoneInput: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
        paddingHorizontal: 10,
        height: 50,
    },
    signupButton: {
        borderRadius: 10,
        paddingVertical: 15,
        width: '100%',
        alignItems: 'center',
        marginBottom: 20,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 3,
    },
    fullWidth: {
        width: '100%',
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    loginText: {
        color: '#888',
        fontSize: 16,
        textAlign: 'center',
        marginTop: 10,
    },
    loginLink: {
        color: '#00ccff',
        textDecorationLine: 'underline',
    },
    eyeIcon: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    // Role Selection Styles
    roleSelectionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
    },
    roleSelectionContent: {
        width: '100%',
        maxWidth: 400,
    },
    roleSelectionTitle: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
    },
    roleSelectionSubtitle: {
        color: '#ccc',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 30,
        lineHeight: 22,
    },
    roleCardsContainer: {
        gap: 20,
        marginBottom: 30,
    },
    roleCard: {
        backgroundColor: 'rgba(51, 51, 51, 0.9)',
        borderRadius: 16,
        padding: 20,
        borderWidth: 2,
        borderColor: 'transparent',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    fanCard: {
        borderColor: '#ff6b9d',
    },
    artistCard: {
        borderColor: '#00ff00',
    },
    roleCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    roleCardTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: 'bold',
        marginLeft: 15,
    },
    roleCardDescription: {
        color: '#ccc',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 15,
    },
    roleFeatures: {
        gap: 8,
    },
    featureItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    featureText: {
        color: '#fff',
        fontSize: 13,
        marginLeft: 8,
    },
    roleSelectionNote: {
        color: '#888',
        fontSize: 12,
        textAlign: 'center',
        fontStyle: 'italic',
    },
});

export default styles;
