import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
        paddingHorizontal: 0,
    },
    text: {
        fontSize: 24,
        color: '#fff',
        marginVertical: 16,
        textAlign: 'center',
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    backButton: {
        padding: 8,
    },
    listContent: {
        paddingBottom: 20,
    },
    notificationItem: {
        backgroundColor: '#18181c',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 16,
        marginHorizontal: 16,
        marginBottom: 14,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.02)',
    },
    unreadNotification: {
        borderColor: '#FF0080',
        borderWidth: 2,
        backgroundColor: '#23232b',
    },
    notificationContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    avatarContainer: {
        marginRight: 16,
        position: 'relative',
    },
    avatar: {
        width: 54,
        height: 54,
        borderRadius: 27,
        borderWidth: 2,
        borderColor: '#23232b',
        backgroundColor: '#222',
    },
    unreadDot: {
        position: 'absolute',
        right: 0,
        bottom: 0,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#FF0080',
        borderWidth: 2,
        borderColor: '#18181c',
    },
    notificationTextContainer: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
    },
    notificationText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
        marginBottom: 2,
        letterSpacing: 0.1,
    },
    notificationMessage: {
        fontSize: 15,
        color: '#bdbdbd',
        fontWeight: '400',
        marginBottom: 2,
    },
    notificationTime: {
        fontSize: 13,
        color: '#888',
        fontWeight: '400',
        marginTop: 2,
    },
    markReadButton: {
        backgroundColor: 'linear-gradient(90deg, #FF0080 0%, #7928CA 100%)',
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 20,
        alignSelf: 'flex-end',
        margin: 16,
        marginBottom: 0,
        shadowColor: '#FF0080',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        shadowRadius: 6,
        elevation: 2,
    },
    markReadText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    emptyText: {
        fontSize: 18,
        color: '#666',
        marginTop: 16,
        textAlign: 'center',
        fontWeight: '500',
    },
    emptyIcon: {
        fontSize: 64,
        color: '#23232b',
        marginBottom: 8,
    },
    errorText: {
        fontSize: 16,
        color: 'red',
        textAlign: 'center',
        marginTop: 20,
    },
    retryButton: {
        padding: 10,
        marginTop: 10,
        backgroundColor: '#007AFF',
        borderRadius: 5,
    },
    retryText: {
        color: 'white',
        fontSize: 16,
    },
});

export default styles;
