import { StyleSheet, Platform, Dimensions } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

const { height } = Dimensions.get('window');
const isSmallDevice = height < 700;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(16),
        paddingTop: isSmallDevice ? verticalScale(30) : verticalScale(40),
        paddingBottom: verticalScale(8),
        backgroundColor: '#000',
    },
    backButton: {
        padding: scale(8),
    },
    headerTitle: {
        color: '#fff',
        fontSize: moderateScale(16),
        fontWeight: '600',
    },
    menuIcon: {
        padding: scale(8),
    },
    profileImageContainer: {
        alignItems: 'center',
        paddingVertical: isSmallDevice ? verticalScale(12) : verticalScale(20),
    },
    imageWrapper: {
        position: 'relative',
    },
    profileImage: {
        width: isSmallDevice ? scale(80) : scale(90),
        height: isSmallDevice ? scale(80) : scale(90),
        borderRadius: isSmallDevice ? scale(40) : scale(45),
        backgroundColor: '#2C2C2E',
    },
    editImageButton: {
        position: 'absolute',
        right: 0,
        bottom: 0,
        backgroundColor: '#2C2C2E',
        width: scale(28),
        height: scale(28),
        borderRadius: scale(14),
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: scale(2),
        borderColor: '#000',
    },
    infoSection: {
        paddingHorizontal: scale(16),
        marginBottom: verticalScale(12),
    },
    sectionTitle: {
        fontSize: moderateScale(18),
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: verticalScale(8),
    },
    infoItem: {
        marginBottom: verticalScale(8),
    },
    label: {
        color: '#8E8E93',
        fontSize: moderateScale(12),
        marginBottom: verticalScale(2),
    },
    input: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(8),
        padding: moderateScale(8),
        color: '#fff',
        fontSize: moderateScale(15),
        height: verticalScale(40),
    },
    actionsSection: {
        paddingHorizontal: 16,
        marginBottom: 24,
    },
    actionButton: {
        backgroundColor: '#1C1C1E',
        borderRadius: 8,
        padding: 16,
        alignItems: 'center',
        marginBottom: 12,
    },
    actionButtonText: {
        color: '#0A84FF',
        fontSize: 17,
        fontWeight: '600',
    },
    submitButton: {
        marginTop: 16,
    },
    logoutButton: {
        marginTop: 8,
    },
    logoutButtonText: {
        color: '#FF453A',
        fontSize: 17,
        fontWeight: '600',
    },
    deleteAccountLink: {
        alignItems: 'center',
        paddingVertical: 16,
        marginBottom: 32,
    },
    deleteAccountText: {
        color: '#8E8E93',
        fontSize: 13,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        paddingHorizontal: scale(16),
    },
    modalContent: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(14),
        padding: scale(20),
    },
    modalTitle: {
        color: '#fff',
        fontSize: moderateScale(17),
        fontWeight: '600',
        marginBottom: verticalScale(8),
        textAlign: 'center',
    },
    modalMessage: {
        color: '#8E8E93',
        fontSize: moderateScale(13),
        marginBottom: verticalScale(16),
        textAlign: 'center',
    },
    modalInput: {
        backgroundColor: '#2C2C2E',
        borderRadius: scale(8),
        padding: moderateScale(12),
        color: '#fff',
        fontSize: moderateScale(16),
        marginBottom: verticalScale(16),
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: scale(8),
    },
    modalButton: {
        flex: 1,
        borderRadius: scale(8),
        padding: moderateScale(12),
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#2C2C2E',
    },
    deleteButton: {
        backgroundColor: '#2C2C2E',
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: moderateScale(16),
        fontWeight: '600',
    },
    deleteButtonText: {
        color: '#FF453A',
        fontSize: moderateScale(16),
        fontWeight: '600',
    },
    optionsModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    optionsBox: {
        backgroundColor: '#1C1C1E',
        borderTopLeftRadius: scale(20),
        borderTopRightRadius: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: Platform.OS === 'ios' ? verticalScale(30) : verticalScale(16),
    },
    optionButton: {
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(20),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#2C2C2E',
    },
    lastOptionButton: {
        borderBottomWidth: 0,
    },
    optionText: {
        color: '#FFFFFF',
        fontSize: moderateScale(16),
        fontWeight: '400',
        textAlign: 'center',
    },
    deleteOptionText: {
        color: '#FF453A',
        fontSize: 17,
        textAlign: 'center',
    },
    logoutOptionText: {
        color: '#FF453A',
        fontSize: 17,
        textAlign: 'center',
    },
    passwordForm: {
        marginTop: 16,
    },
    blockedUserAvatar: {
        width: scale(40),
        height: verticalScale(40),
        borderRadius: scale(20),
        marginRight: scale(8),
        borderWidth: scale(1),
        borderColor: '#D500F9',
    },
    blockedUserContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: verticalScale(8),
        padding: scale(8),
        backgroundColor: '#1C1C1E',
        borderRadius: scale(6),
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    logo: {
        width: scale(75),
        height: verticalScale(75),
        resizeMode: 'contain',
        marginTop: verticalScale(5),
    },
    profileSection: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(10),
        padding: verticalScale(15),
        alignItems: 'center',
        width: '100%',
        alignSelf: 'stretch',
    },
    signatureSection: {
        paddingHorizontal: scale(16),
        marginBottom: verticalScale(16),
    },
    signatureButtonsContainer: {
        flexDirection: 'row',
        gap: scale(8),
        marginTop: verticalScale(8),
    },
    signatureButton: {
        flex: 1,
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        padding: scale(12),
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: isSmallDevice ? verticalScale(80) : verticalScale(100),
    },
    signatureButtonContent: {
        alignItems: 'center',
        gap: scale(6),
    },
    signatureButtonText: {
        color: '#FFFFFF',
        fontSize: moderateScale(13),
        fontWeight: '500',
        textAlign: 'center',
        opacity: 0.9,
    },
    signatureCreationContainer: {
        marginTop: verticalScale(15),
    },
    signaturePreview: {
        width: '100%',
        height: verticalScale(200),
        borderRadius: scale(10),
        backgroundColor: '#1C1C1E',
        marginBottom: verticalScale(15),
    },
    placeholderText: {
        color: '#8E8E93',
        textAlign: 'center',
        marginVertical: verticalScale(15),
    },
    signatureOptions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: verticalScale(15),
    },
    createButton: {
        backgroundColor: '#4A90E2',
        padding: verticalScale(12),
        borderRadius: scale(8),
        marginTop: verticalScale(10),
    },
    createButtonText: {
        color: '#FFFFFF',
        textAlign: 'center',
        fontSize: moderateScale(16),
        fontWeight: '600',
    },
    modalButtonText: {
        color: '#FFF',
        fontWeight: '400',
        fontSize: moderateScale(16),
        paddingLeft: 60,
    },
    imageContainer: {
        width: '100%',
        height: verticalScale(200),
        borderRadius: scale(10),
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: verticalScale(15),
    },
    image: {
        width: '100%',
        height: '100%',
        borderRadius: scale(10),
    },
    imageText: {
        color: '#FFFFFF',
        fontSize: moderateScale(16),
        textAlign: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: verticalScale(15),
    },
    pictureButton: {
        flex: 1,
        backgroundColor: '#1C1C1E',
        borderRadius: scale(10),
        padding: verticalScale(15),
        alignItems: 'center',
        marginHorizontal: scale(5),
    },
    icon: {
        marginBottom: verticalScale(8),
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: moderateScale(14),
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: scale(10),
    },
    loadingContainer: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    loadingContent: {
        alignItems: 'center',
        width: '100%',
        maxWidth: scale(280),
        padding: scale(20),
    },
    loadingIcon: {
        width: scale(60),
        height: scale(60),
        marginBottom: verticalScale(16),
        resizeMode: 'contain',
    },
    loadingMainText: {
        color: '#FFFFFF',
        fontSize: moderateScale(18),
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: verticalScale(6),
    },
    loadingSubText: {
        color: '#8E8E93',
        fontSize: moderateScale(13),
        textAlign: 'center',
        marginBottom: verticalScale(16),
    },
    progressBarContainer: {
        width: '80%',
        height: verticalScale(2),
        backgroundColor: '#2C2C2E',
        borderRadius: scale(1),
        overflow: 'hidden',
    },
    progressBar: {
        height: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: scale(1),
    },
    fanSection: {
        marginTop: verticalScale(20),
        paddingHorizontal: scale(16),
    },
    quickActionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: verticalScale(16),
    },
    quickActionButton: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        padding: scale(16),
        flex: 1,
        marginHorizontal: scale(8),
    },
    quickActionContent: {
        alignItems: 'center',
    },
    quickActionText: {
        color: '#FFFFFF',
        fontSize: moderateScale(14),
        marginTop: verticalScale(8),
        textAlign: 'center',
    },
    featuredCollectionsContainer: {
        marginTop: verticalScale(24),
    },
    collectionCard: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        marginBottom: verticalScale(16),
        overflow: 'hidden',
    },
    collectionImage: {
        width: '100%',
        height: verticalScale(120),
        resizeMode: 'cover',
    },
    collectionInfo: {
        padding: scale(16),
    },
    collectionTitle: {
        color: '#FFFFFF',
        fontSize: moderateScale(18),
        fontWeight: '600',
        marginBottom: verticalScale(4),
    },
    collectionDescription: {
        color: '#8E8E93',
        fontSize: moderateScale(14),
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: verticalScale(24),
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        padding: scale(16),
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        color: '#FFFFFF',
        fontSize: moderateScale(20),
        fontWeight: 'bold',
    },
    statLabel: {
        color: '#8E8E93',
        fontSize: moderateScale(12),
        marginTop: verticalScale(4),
    },
    recentActivityContainer: {
        marginTop: verticalScale(24),
    },
    subSectionTitle: {
        color: '#FFFFFF',
        fontSize: moderateScale(16),
        fontWeight: '600',
        marginBottom: verticalScale(16),
    },
    activityList: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        padding: scale(16),
        minHeight: verticalScale(100),
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyActivityText: {
        color: '#8E8E93',
        fontSize: moderateScale(14),
    },
    userLogoSection: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: verticalScale(40),
        paddingHorizontal: scale(20),
    },
    userLogo: {
        width: scale(200),
        height: scale(200),
        resizeMode: 'contain',
    },
    connectedArtistsSection: {
        paddingHorizontal: scale(16),
        marginBottom: verticalScale(16),
    },
    artistsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: verticalScale(8),
    },
    artistCard: {
        width: '48%',
        backgroundColor: '#1C1C1E',
        borderRadius: scale(12),
        padding: scale(10),
        marginBottom: verticalScale(8),
        alignItems: 'center',
    },
    artistAvatar: {
        width: scale(50),
        height: scale(50),
        borderRadius: scale(25),
        marginBottom: verticalScale(6),
    },
    artistName: {
        color: '#FFFFFF',
        fontSize: moderateScale(12),
        fontWeight: '500',
        textAlign: 'center',
    },
    noArtistsText: {
        color: '#8E8E93',
        fontSize: moderateScale(13),
        textAlign: 'center',
        marginTop: verticalScale(12),
    },
});

export default styles;
