import { StyleSheet } from 'react-native';
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';


const styles = StyleSheet.create({
    container: {
        paddingTop: scale(31),
        flex: 1,
        backgroundColor: '#000',
        padding: scale(15), // Compact padding for the overall layout
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#1C1C1E',
        padding: scale(15),
        borderRadius: scale(8),
        width: '100%',
        alignItems: 'center',
    },
    modalHeader: {
        fontSize: moderateScale(18),
        color: '#FFF',
        fontWeight: 'bold',
        marginBottom: verticalScale(8),
    },
    modalMessage: {
        fontSize: moderateScale(14),
        color: '#FFF',
        textAlign: 'center',
        marginBottom: verticalScale(15),
    },
    modalInput: {
        backgroundColor: '#2C2C2E',
        color: '#FFF',
        padding: verticalScale(8),
        borderRadius: scale(6),
        width: '100%',
        textAlign: 'center',
        marginBottom: verticalScale(15),
    },
    homeButton: {
        position: 'absolute',
        top: verticalScale(15),
        left: scale(15),
        padding: scale(8),
        zIndex: 10,
    },
    blockedUserAvatar: {
        width: scale(40),
        height: verticalScale(40),
        borderRadius: scale(20),
        marginRight: scale(8),
        borderWidth: scale(1),
        borderColor: '#D500F9',
    },
    optionsModalContainer: {
        flex: 1,
        backgroundColor: 'transparent',
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
    },
    optionsBox: {
        backgroundColor: '#1C1C1E',
        padding: scale(8),
        borderRadius: scale(8),
        marginTop: verticalScale(40),
        marginRight: scale(15),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.5,
        shadowRadius: 4,
        elevation: 5,
    },
    optionButton: {
        paddingVertical: verticalScale(8),
        paddingHorizontal: scale(15),
    },
    optionText: {
        fontSize: moderateScale(14),
        color: '#FFF',
    },
    blockedUserContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: verticalScale(8),
        padding: scale(8),
        backgroundColor: '#1C1C1E',
        borderRadius: scale(6),
    },
    menuIcon: {
        position: 'absolute',
        top: verticalScale(15),
        right: scale(15),
        padding: scale(8),
        zIndex: 10,
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    logo: {
        width: scale(75),
        height: verticalScale(75),
        resizeMode: 'contain',
        marginTop: verticalScale(5),
    },
    profileSection: {
        backgroundColor: '#1C1C1E',
        borderRadius: scale(10),
        padding: verticalScale(15),
        alignItems: 'center',
        width: '100%',
        alignSelf: 'stretch',
    },
    sectionTitle: {
        color: '#FFFFFF',
        fontSize: moderateScale(20),
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: verticalScale(12),
    },
    profilePicture: {
        width: scale(90),
        height: verticalScale(90),
        borderRadius: scale(45),
        marginBottom: verticalScale(10),
        borderWidth: scale(2),
        borderColor: '#D500F9',
    },
    input: {
        backgroundColor: '#2C2C2E',
        color: '#FFF',
        padding: verticalScale(8),
        marginVertical: verticalScale(6),
        borderRadius: scale(6),
        width: '100%',
        textAlign: 'center',
        fontSize: moderateScale(14),
    },
    line: {
        width: '100%',
        height: verticalScale(1),
        backgroundColor: '#444',
        marginVertical: verticalScale(10),
    },
    gradientButtonFullWidth: {
        paddingVertical: verticalScale(8),
        borderRadius: scale(6),
        alignItems: 'center',
        marginVertical: verticalScale(6),
        width: '100%',
    },
    buttonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: moderateScale(14),
    },
    logoutButton: {
        backgroundColor: '#FF453A',
        paddingVertical: verticalScale(10),
        borderRadius: scale(8),
        alignItems: 'center',
        marginVertical: verticalScale(10),
        width: '100%',
        alignSelf: 'stretch',
    },
    logoutButtonText: {
        color: '#FFF',
        fontWeight: '600',
        fontSize: moderateScale(14),
    },
    passwordForm: {
        width: '100%',
        marginTop: verticalScale(8),
    },
    blockedUserText: {
        color: '#FFF',
        fontSize: moderateScale(14),
    },
    unblockButton: {
        backgroundColor: '#D500F9',
        padding: scale(8),
        borderRadius: scale(6),
    },
    unblockButtonText: {
        color: '#FFF',
    },
    closeModalButton: {
        marginTop: verticalScale(15),
        padding: scale(10),
        backgroundColor: '#FF453A',
        borderRadius: scale(8),
        alignItems: 'center',
    },
    closeModalText: {
        color: '#FFF',
        fontSize: moderateScale(14),
        fontWeight: '600',
    },
    deleteAccountButton: {
        backgroundColor: '#FF3B30',
        paddingVertical: verticalScale(10),
        borderRadius: scale(8),
        alignItems: 'center',
        marginVertical: verticalScale(8),
        width: '100%',
        alignSelf: 'stretch',
    },
    deleteAccountButtonText: {
        color: '#FFF',
        fontWeight: '600',
        fontSize: moderateScale(14),
    },
});

export default styles
