import { StyleSheet, Platform, Dimensions } from "react-native";
import { scale, verticalScale, moderateScale } from 'react-native-size-matters';

const styles = StyleSheet.create({
    container: { 
        flex: 1, 
        backgroundColor: '#000000',
    },
    loaderContainer: { 
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        backgroundColor: '#000000' 
    },
    errorText: { 
        color: '#FFFFFF', 
        fontSize: moderateScale(16),
        textAlign: 'center',
        marginTop: verticalScale(20),
    },
    
    // Header Section
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        backgroundColor: '#000000',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#1a1a1a',
    },
    postTitle: { 
        color: '#FFFFFF', 
        fontSize: moderateScale(18), 
        fontWeight: '600',
        flex: 1,
        textAlign: 'center',
        letterSpacing: -0.3,
    },
    plusIcon: { 
        padding: scale(8),
        width: scale(40),
        height: scale(40),
        justifyContent: 'center',
        alignItems: 'center',
    },
    
    // Post Card
    postCard: {
        backgroundColor: '#0f0f0f',
        marginVertical: verticalScale(8),
        borderRadius: scale(12),
        marginHorizontal: scale(16),
        paddingBottom: verticalScale(8),
        borderWidth: 1,
        borderColor: '#1a1a1a',
    },
    userInfoContainer: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
    },
    avatar: { 
        width: scale(32), 
        height: scale(32), 
        borderRadius: scale(16), 
        marginRight: scale(12),
        backgroundColor: '#1a1a1a',
    },
    userName: { 
        fontSize: moderateScale(14), 
        fontWeight: '600', 
        color: '#FFFFFF',
        marginBottom: scale(2),
        letterSpacing: -0.2,
    },
    userLocation: { 
        fontSize: moderateScale(12), 
        color: '#8E8E8E',
        letterSpacing: -0.1,
    },
    postText: { 
        fontSize: moderateScale(14), 
        color: '#FFFFFF', 
        paddingHorizontal: scale(16),
        paddingBottom: verticalScale(12),
        lineHeight: moderateScale(20),
        letterSpacing: -0.1,
    },
    postImage: { 
        width: '100%', 
        height: verticalScale(400), 
        backgroundColor: '#1a1a1a',
    },
    interactionRow: { 
        flexDirection: 'row', 
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#1a1a1a',
    },
    iconText: { 
        marginLeft: scale(6), 
        fontSize: moderateScale(13), 
        color: '#FFFFFF',
        fontWeight: '400',
    },
    
    // Artist Comments Section - Now styled as Post Cards
    artistCommentsSection: {
        marginBottom: verticalScale(16),
        paddingHorizontal: scale(16),
    },
    artistPostCard: {
        backgroundColor: '#0f0f0f',
        marginBottom: verticalScale(16),
        borderRadius: scale(12),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(8),
        borderWidth: 1,
        borderColor: '#1a1a1a',
    },
    artistRepliesContainer: {
        marginTop: verticalScale(12),
        paddingTop: verticalScale(12),
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#1a1a1a',
        backgroundColor: '#0a0a0a',
        marginHorizontal: scale(-16),
        paddingHorizontal: scale(16),
        paddingBottom: verticalScale(8),
        borderBottomLeftRadius: scale(12),
        borderBottomRightRadius: scale(12),
        maxHeight: verticalScale(200),
        overflow: 'hidden',
    },
    repliesHeader: {
        paddingBottom: verticalScale(8),
        marginBottom: verticalScale(8),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#1a1a1a',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    repliesHeaderText: {
        fontSize: moderateScale(13),
        fontWeight: '600',
        color: '#8E8E8E',
        letterSpacing: -0.1,
    },
    scrollableRepliesContainer: {
        maxHeight: verticalScale(150),
    },
    replyBoxContainer: {
        marginTop: verticalScale(12),
        paddingTop: verticalScale(12),
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: '#1a1a1a',
        backgroundColor: '#0a0a0a',
        marginHorizontal: scale(-16),
        paddingHorizontal: scale(16),
        paddingBottom: verticalScale(8),
        borderBottomLeftRadius: scale(12),
        borderBottomRightRadius: scale(12),
    },
    replyBoxScrollContainer: {
        maxHeight: verticalScale(450),
        borderRadius: scale(8),
        overflow: 'hidden',
    },
    replyCard: {
        backgroundColor: '#0a0a0a',
        marginBottom: verticalScale(8),
        padding: scale(12),
        borderRadius: scale(8),
        borderWidth: 1,
        borderColor: '#1a1a1a',
    },
    
    // Comments Section
    commentsSection: {
        backgroundColor: '#000000',
        paddingTop: verticalScale(16),
    },
    commentsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(16),
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: '#1a1a1a',
    },
    commentsHeaderText: {
        fontSize: moderateScale(14),
        fontWeight: '600',
        color: '#FFFFFF',
        letterSpacing: -0.2,
    },
    commentContainer: {
        backgroundColor: '#0f0f0f',
        marginHorizontal: scale(16),
        marginBottom: verticalScale(12),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        borderRadius: scale(12),
        borderWidth: 1,
        borderColor: '#1a1a1a',
    },
    commentText: { 
        color: '#FFFFFF', 
        marginTop: verticalScale(4), 
        fontSize: moderateScale(14),
        lineHeight: moderateScale(20),
        letterSpacing: -0.1,
    },
    fanCommentText: { 
        color: '#FFFFFF',
    },
    commentImage: { 
        width: '100%', 
        height: verticalScale(200), 
        borderRadius: scale(8), 
        marginVertical: verticalScale(8),
        backgroundColor: '#1a1a1a',
    },
    commentAImage: {
        width: scale(120),
        height: scale(120),
        borderRadius: scale(8),
        marginVertical: verticalScale(8),
        backgroundColor: '#1a1a1a',
        alignSelf: 'flex-start',
    },
    commentVideo: {
        width: scale(120),
        height: scale(120),
        borderRadius: scale(8),
        marginVertical: verticalScale(8),
        backgroundColor: '#1a1a1a',
        alignSelf: 'flex-start',
    },
    
    // Replies Section
    repliesContainer: { 
        paddingLeft: scale(32), 
        marginTop: verticalScale(8),
        borderLeftWidth: 2,
        borderLeftColor: '#1a1a1a',
        maxHeight: verticalScale(300),
        overflow: 'hidden',
    },
    scrollableRepliesList: {
        maxHeight: verticalScale(250),
    },
    reply: { 
        marginBottom: verticalScale(8),
        paddingVertical: verticalScale(8),
    },
    replyText: { 
        color: '#FFFFFF', 
        fontSize: moderateScale(14),
        lineHeight: moderateScale(20),
        marginTop: verticalScale(4),
        letterSpacing: -0.1,
    },
    replyTimestamp: { 
        color: '#8E8E8E', 
        fontSize: moderateScale(11),
        marginTop: verticalScale(4),
    },
    dropdownButton: { 
        paddingVertical: verticalScale(8), 
        marginTop: verticalScale(4),
    },
    dropdownText: { 
        color: '#FF0080', 
        fontSize: moderateScale(13),
        fontWeight: '500',
    },
    
    // Interaction Icons
    dotsButton: {
        marginHorizontal: scale(8),
    },
    
    // Modal Styles
    modalBackground: { 
        flex: 1, 
        justifyContent: 'flex-end', 
        backgroundColor: 'rgba(0, 0, 0, 0.7)' 
    },
    modalContainer: { 
        width: '100%', 
        backgroundColor: '#1a1a1a', 
        borderTopLeftRadius: scale(20), 
        borderTopRightRadius: scale(20),
        paddingTop: verticalScale(20),
        paddingBottom: verticalScale(40),
        paddingHorizontal: scale(20),
        maxHeight: '90%',
    },
    modalTitle: { 
        fontSize: moderateScale(18), 
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: verticalScale(20),
        textAlign: 'center',
        letterSpacing: -0.3,
    },
    textInput: {
        width: '100%',
        minHeight: verticalScale(100),
        borderColor: '#333333',
        borderWidth: 1,
        borderRadius: scale(8),
        padding: scale(12),
        marginBottom: verticalScale(16),
        fontSize: moderateScale(15),
        color: '#FFFFFF',
        backgroundColor: '#000000',
        textAlignVertical: 'top',
        letterSpacing: -0.1,
    },
    iconRow: { 
        flexDirection: 'row', 
        justifyContent: 'center', 
        width: '100%', 
        marginBottom: verticalScale(20),
        gap: scale(24),
    },
    postButton: {
        backgroundColor: '#FF0080',
        paddingVertical: verticalScale(12),
        borderRadius: scale(8),
        width: '100%',
        alignItems: 'center',
        marginBottom: verticalScale(12),
    },
    postButtonText: { 
        color: '#FFFFFF', 
        fontWeight: '600',
        fontSize: moderateScale(15),
        letterSpacing: -0.2,
    },
    closeButton: { 
        marginTop: verticalScale(8),
        paddingVertical: verticalScale(12),
    },
    closeButtonText: { 
        color: '#FFFFFF', 
        fontWeight: '600',
        fontSize: moderateScale(15),
        textAlign: 'center',
    },
    mediaContainer: {
        position: 'relative',
        width: scale(150),
        height: scale(150),
        marginBottom: verticalScale(16),
        borderRadius: scale(8),
        overflow: 'hidden',
        backgroundColor: '#1a1a1a',
    },
    mediaPreview: {
        width: '100%',
        height: '100%',
        borderRadius: scale(8),
        backgroundColor: '#1a1a1a',
    },
    clearButton: {
        position: 'absolute',
        top: scale(8),
        right: scale(8),
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: scale(15),
        width: scale(30),
        height: scale(30),
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1,
    },
    
    // Report Modal Styles
    reportModalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    reportModalContainer: {
        backgroundColor: '#1a1a1a',
        borderRadius: scale(12),
        padding: scale(24),
        width: '85%',
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: '#333333',
    },
    reportModalTitle: {
        fontSize: moderateScale(18),
        fontWeight: '600',
        color: '#FFFFFF',
        marginBottom: verticalScale(16),
        letterSpacing: -0.3,
    },
    reportModalDescriptionInput: {
        backgroundColor: '#000000',
        color: '#FFFFFF',
        padding: scale(12),
        borderRadius: scale(8),
        height: verticalScale(100),
        marginBottom: verticalScale(20),
        textAlignVertical: 'top',
        fontSize: moderateScale(15),
        borderWidth: 1,
        borderColor: '#333333',
        letterSpacing: -0.1,
    },
    reportModalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        gap: scale(12),
    },
    reportModalCancelButton: {
        backgroundColor: '#333333',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(20),
        borderRadius: scale(8),
        flex: 1,
    },
    reportModalCancelButtonText: {
        color: '#FFFFFF',
        fontSize: moderateScale(15),
        textAlign: 'center',
        fontWeight: '600',
        letterSpacing: -0.2,
    },
    reportModalSubmitButton: {
        backgroundColor: '#ED4956',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(20),
        borderRadius: scale(8),
        flex: 1,
    },
    reportModalButtonText: {
        color: '#FFFFFF',
        fontSize: moderateScale(15),
        textAlign: 'center',
        fontWeight: '600',
        letterSpacing: -0.2,
    },
    
    // Report Menu Styles
    reportMenuOverlay: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        paddingTop: verticalScale(50),
        paddingRight: scale(16),
    },
    reportMenuContainer: {
        backgroundColor: '#1a1a1a',
        borderRadius: scale(12),
        paddingVertical: verticalScale(8),
        width: scale(200),
        borderWidth: 1,
        borderColor: '#333333',
    },
    reportMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(16),
        width: '100%',
    },
    reportMenuFlagIcon: {
        marginRight: scale(12),
    },
    reportMenuText: {
        fontSize: moderateScale(15),
        color: '#FFFFFF',
        fontWeight: '400',
        letterSpacing: -0.1,
    },
    
    // Collapse Text
    collapseText: { 
        color: '#FFFFFF', 
        textAlign: 'center', 
        marginVertical: verticalScale(10), 
        fontSize: moderateScale(14), 
        fontWeight: '600' 
    },
});

export default styles;
